name: "RTL_433 Discover and Submit"
version: "0.1.0"
slug: "rtl_433_discover_and_submit"
description: "Automatically discover wireless sensors with rtl_433 and add them to Home Assistant"
url: "https://github.com/dewgenenny/rtl_433_discoverandsubmit"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
map:
  - share:rw
services:
  - mqtt:need
devices:
  - /dev/bus/usb:/dev/bus/usb:rwm
options:
  mqtt_discovery_prefix: "homeassistant"
  mqtt_topic_prefix: "rtl_433"
  mqtt_retain: true
  rtl_433_advanced_params: ""
  rtl_433_protocol_params: ""
  log_level: "INFO"
schema:
  mqtt_discovery_prefix: str
  mqtt_topic_prefix: str
  mqtt_retain: bool
  rtl_433_advanced_params: str
  rtl_433_protocol_params: str
  log_level: list(TRACE|DEBUG|INFO|WARNING|ERROR|FATAL)
